datasets:

- name: atsans_blueprint_account_dataset
  description: "This bucket holds account data for the lake"
  labels:
  - sample
  - ingress
  admin:
  - ingestionservice@atsans.com
  reader:
  - ingestionservice@atsans.com
  location: australia-southeast1
